### PR TITLE
feat: ring alarm api

### LINKED ISSUE #8: Ring Alarm API
Hi,

Are you looking to add Ring Alarm support to your API? Would be amazing!

Thanks,

Philipp

### PR DESCRIPTION
**Pull request by dgreif**
## Ring Alarm
 - Get alarms from all ring locations
 - Get devices for each alarm
 - Arm/disarm alarm with optional bypass of specific sensors
 - Subscribe to data updates on individual devices
 - Change volume on base station and keypad
 - Flattened data structure for returned device data.  Original format from ring is cumbersome to interact with

## Other Enhancements
 - Editorconfig consisten with existing code style
 - Re-fetching of auth token if it appears to have expired
 - OAuth requests using `Bearer token` auth header
 - Retrying api calls if the endpoint is unreachable (for cases where internet connection is interrupted)
 - Typescript `.d.ts` file added.  Currently only contains types for my alarm additions

Closes #8 

Sorry for the long delay on this, haven't had much free time lately.  Looks like @mrose17 has a different implementation based on doorbot over at https://github.com/homespun/ring-alarm now.  Personally, I think your base library setup is cleaner and more modern so I think it's still worth adding alarm functionality here.  For anyone interested in a homebridge plugin, I have one ready to go that I will be publishing in the next couple days (probably waiting until this PR is merged).

### CODE REVIEW

**Comment by mrose17** [comment]
@dgreif - thanks for the reply! i was planning on writing a ring alarm homebridge plugin during november, but now i don't have too!

**Comment by dgreif** [comment]
@mrose17 I've published [`homebridge-ring-alarm`](https://github.com/dgreif/homebridge-ring-alarm) using my fork of the api for now.  It's my first attempt at a homebridge plugin so any feedback/issues/PRs are appreciated!

**Comment by psifertex** [comment]
Been a while with no updates. Anything blocking a merge on this?

**Comment by jogibear9988** [comment]
@jimhigson could you merge please?

**Comment by dgreif** [comment]
I've been using my repo in https://github.com/dgreif/homebridge-ring-alarm for 2 months with no issues.  Should be ready to merge any time @jimhigson

**Comment by dgreif** [comment]
Since @jimhigson is unresponsive, I decided to just pull the ring alarm into it's own repo.  I've got a new repo that houses both the alarm api and the `homebridge-ring-alarm` plugin at https://github.com/dgreif/ring-alarm.

**Comment by joeyeng** [comment]
Wow, great work on this @dgreif! I used this to update my ip cams home/away mode (Blue Iris) based on the Ring alarm mode and it's working flawlessly.

**Pull request closed without merging**
